# analyze real GDP growth and yield curve data
library(tis)
# yield curve data
yc <- read.csv("ycdata.csv")
ycts <- ts(yc[,2:3], start = c(1959, 1), frequency = 12)
head(ycts)
ts.plot(ycts, lty = 1:2)
title(main="monthly")
abline(h=0, col = "gray60")
legend("topleft",legend=c("bill","bond"), lty = 1:2)
# convert monthly to quarterly data
ycq<-aggregate(ycts,nfrequency = 4,FUN = mean)
ts.plot(ycq, lty = 1:2)
title(main="quarterly")
abline(h=0, col = "gray60")
legend("topleft",legend=c("bill","bond"), lty = 1:2)
# correlation diagnostics
acf(ycq[,1])
pacf(ycq[,1])
acf(diff(ycq[,1]))
acf(ycq[,2])
pacf(ycq[,2])
acf(diff(ycq[,2]))
ccf(ycq[,1],ycq[,2])
ccf(diff(ycq[,1]),diff(ycq[,2]))
# GDP data
yp <- read.csv("ycQ.csv")
yts <- ts(yp[,2], start = c(1947, 1), frequency = 4)
head(yts)
plot(yts)
plot(log(yts))
acf(yts)
acf(log(yts))
pacf(log(yts))
acf(diff(log(yts)))
# GDP growth over next year
dy4<-100*(lag(log(yts),4)-log(yts))
# GDP growth over last year
dy4led<-lag(dy4,-4)
plot(yts)
plot(log(yts))
plot(dy4led)
acf(dy4)
pacf(dy4)
# fit trend
trend<-ts(1:length(yts), start = c(1947, 1), frequency = 4)
ydetrd<-lm(log(yts)~trend)
summary(ydetrd)
ts.plot(log(yts),fitted(ydetrd),lty=1:2)
plot(residuals(ydetrd),type="l")
# gdp and business cycle
plot(dy4led)
nberShade()
abline(h=0, col = "gray60")
par(new=TRUE)
plot(dy4led)
# yield curve spread
spr<-ycq[,2]-ycq[,1]
plot(spr)
nberShade()
abline(h=0, col = "gray60")
par(new=TRUE)
plot(spr)
acf(spr)
pacf(spr)
# fancy graph of dy4 and spr
dg<-ts.union(dy4,spr)
dgw<-window(dg,1959,c(2015,4))
par(mar=c(5,4,4,5)+.1)
ts.plot(dgw[,1],col="red",ylab="GDP growth",ylim=c(-5,10))
abline(h=0, col = "gray60")
par(new=TRUE)
ts.plot(dgw[,2],col="blue",gpars=list(axes=F,xlab="",ylab="",ylim=c(-2,4)))
axis(4)
mtext("spread",side=4,line=3)
legend("bottomleft",col=c("red","blue"),lty=1,legend=c("GDP gr","spread"))
